spring.application.name=conectaPro-api
 
server.port=${PORT:8080}
spring.config.import=optional:file:.env[.properties]
 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${HOST_DB}:${PORT_DB}/${NAME_DB}
spring.datasource.username=${USER_DB:postgres}
spring.datasource.password=${PASS_DB}
 
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.generate-ddl=true
 
# SWAGGER
springdoc.api-docs.path=/api-docs
 
# GEOAPIFY (Latitude e Longitude)
geoapify.url=${GEOCODE_URL}
geoapify.key=${GEOCODE_KEY}
 
# Upload de IMG (Cloudflare R2)
r2.account.id=${R2_ACCOUNT_ID}
r2.access.key.id=${R2_ACCESS_KEY_ID}
r2.secret.access.key=${R2_SECRET_ACCESS_KEY}
r2.bucket.name=${R2_BUCKET_NAME}
# Tamanho máximo permitido para um único arquivo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
 
# E-mail
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASS}
 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 
# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
