spring.application.name=conectaPro-api

server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${HOST_DB}:${PORT_DB}/${NAME_DB}
spring.datasource.username=postgres
spring.datasource.password=${PASS_DB}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.generate-ddl=true

springdoc.api-docs.path=/api-docs

geoapify.url=https://api.geoapify.com/v1/geocode/search
geoapify.key=618268faeaf941159a35105b165ed717

# Tamanho máximo permitido para um único arquivo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB